DROP TABLE IF EXISTS table_user;
CREATE TABLE table_user (
   ID             INT(11) NOT NULL AUTO_INCREMENT,
   EMAIL          VARCHAR(100) NOT NULL,
   PASSWORD       VARCHAR(100) NOT NULL,
   FIRSTNAME      VARCHAR(50),
   LASTNAME       VARCHAR(50),
   PROFILE_IMAGE  VARCHAR(100),
   CONSTRAINT PK_USER PRIMARY KEY (ID)
);